camera_node:
  ros__parameters:
    camera_index: 0        # индекс камеры (0 = первая USB)
    width: 640             # разрешение
    height: 480
    fps: 10
    compressed: true       # публиковать как CompressedImage
